# Generated by Django 3.1.2 on 2020-10-31 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalleCombustible', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoUso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalleUso', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMarca', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransmision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalleTrasmision', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalleTipoVehiculo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to='')),
                ('modelo', models.CharField(max_length=45)),
                ('precio', models.IntegerField()),
                ('combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.combustible')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.marca')),
                ('tipoVehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.tipovehiculo')),
                ('transmision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.tipotransmision')),
                ('uso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.estadouso')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
