# Generated by Django 3.1.2 on 2020-11-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_auto_20201103_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='usuario',
        ),
    ]
