# Generated by Django 3.1.2 on 2020-11-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_remove_vehiculo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
