# Generated by Django 3.1.2 on 2020-11-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_auto_20201103_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='foto',
            field=models.ImageField(upload_to='imagens'),
        ),
    ]
