# Generated by Django 3.1.2 on 2020-11-04 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=45)),
                ('tipoVehiculo', models.CharField(max_length=45)),
                ('combustible', models.CharField(max_length=45)),
                ('transmision', models.CharField(max_length=45)),
                ('precio', models.PositiveIntegerField()),
                ('uso', models.CharField(max_length=45)),
                ('imagen', models.ImageField(upload_to='imagens')),
                ('fechaSubida', models.DateField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
